experimento: 9017.0
semilla_primigenia: 999199.0
semillas:
- 999199.0
- 999499.0
- 999599.0
- 999959.0
- 999979.0
train:
- 202101.0
- 202102.0
- 202103.0
train_final:
- 202102.0
- 202101.0
- 202103.0
future: 202106.0
false_future: 202104.0
semilla_kaggle: 314159.0
cortes:
- 6000.0
- 6500.0
- 7000.0
- 7500.0
- 8000.0
- 8500.0
- 9000.0
- 9500.0
- 10000.0
- 10500.0
- 11000.0
- 11500.0
- 12000.0
- 12500.0
- 13000.0
- 13500.0
- 14000.0
- 14500.0
- 15000.0
- 15500.0
- 16000.0
- 16500.0
- 17000.0
- 17500.0
- 18000.0
trainingstrategy:
  undersampling: 0.2
hyperparametertuning:
  xval_folds: 5.0
lgbm:
  param_fijos:
    boosting: gbdt
    objective: binary
    metric: auc
    first_metric_only: no
    boost_from_average: yes
    feature_pre_filter: no
    force_row_wise: yes
    verbosity: -100.0
    seed: 999199.0
    max_depth: -1
    min_gain_to_split: 0.0
    min_sum_hessian_in_leaf: 0.001
    lambda_l1: 0.0
    lambda_l2: 0.0
    max_bin: 31
    bagging_fraction: 1.0
    pos_bagging_fraction: 1.0
    neg_bagging_fraction: 1.0
    is_unbalance: no
    scale_pos_weight: 1.0
    drop_rate: 0.1
    max_drop: 50.0
    skip_drop: 0.5
    extra_trees: no
    num_iterations: 1200.0
    learning_rate: 0.02
    feature_fraction: 0.5
    num_leaves: 750.0
    min_data_in_leaf: 5000.0
out:
  lgbm:
    mejores_hiperparametros:
      num_iterations: 3158.0
      learning_rate: 0.0171
      feature_fraction: 0.904
      num_leaves: 372.0
      min_data_in_leaf: 3.0
      max_depth: 12.0
      min_gain_to_split: 0.000113
      lambda_l1: 0.015
      lambda_l2: 7.11
      bagging_fraction: 0.949
      bagging_freq: 4.0
